### ISSUE TITLE
dictionary.py attribute error

### ISSUE THREAD

**Issue by ellenclary** [arieb/python-testdata#9]
Using Python 3.5.2 and 3.6.1 shows this error:

Traceback (most recent call last):
  File "./testdata-gen.py", line 13, in <module>
    for user in Users().generate(4): # Generate 4 users
  File "/anaconda/lib/python3.5/site-packages/testdata/dictionary.py", line 27, in __init__
    self._child_factories = deepcopy(self._child_factory_tree)
AttributeError: 'Users' object has no attribute '_child_factory_tree'

$ python --version
Python 3.5.2 :: Anaconda 4.2.0 (x86_64)

**Comment by jin1205** [comment]
I got the same error when using python3.6.1, but no errors if using python 2.7.10

**Comment by phouse512** [comment]
Same here, this library does not seem to work with python 3 (>= 3.5??).
